In [1]:
import pandas as pd

In [2]:
df = pd.read_table('../../data/SOCR_MLB.tsv')
df

        Adam_Donachie  BAL         Catcher  74    180  22.99
0           Paul_Bako  BAL         Catcher  74  215.0  34.69
1     Ramon_Hernandez  BAL         Catcher  72  210.0  30.78
2        Kevin_Millar  BAL   First_Baseman  72  210.0  35.43
3         Chris_Gomez  BAL   First_Baseman  73  188.0  35.71
4       Brian_Roberts  BAL  Second_Baseman  69  176.0  29.39
...               ...  ...             ...  ..    ...    ...
1028    Brad_Thompson  STL  Relief_Pitcher  73  190.0  25.08
1029    Tyler_Johnson  STL  Relief_Pitcher  74  180.0  25.73
1030   Chris_Narveson  STL  Relief_Pitcher  75  205.0  25.19
1031    Randy_Keisler  STL  Relief_Pitcher  75  190.0  31.01
1032      Josh_Kinney  STL  Relief_Pitcher  73  195.0  27.92

[1033 rows x 6 columns]

In [3]:
df.columns = ['Name', 'Team', 'Role', 'Weight', 'Height', 'Age']
df

                 Name Team            Role  Weight  Height    Age
0           Paul_Bako  BAL         Catcher      74   215.0  34.69
1     Ramon_Hernandez  BAL         Catcher      72   210.0  30.78
2        Kevin_Millar  BAL   First_Baseman      72   210.0  35.43
3         Chris_Gomez  BAL   First_Baseman      73   188.0  35.71
4       Brian_Roberts  BAL  Second_Baseman      69   176.0  29.39
...               ...  ...             ...     ...     ...    ...
1028    Brad_Thompson  STL  Relief_Pitcher      73   190.0  25.08
1029    Tyler_Johnson  STL  Relief_Pitcher      74   180.0  25.73
1030   Chris_Narveson  STL  Relief_Pitcher      75   205.0  25.19
1031    Randy_Keisler  STL  Relief_Pitcher      75   190.0  31.01
1032      Josh_Kinney  STL  Relief_Pitcher      73   195.0  27.92

[1033 rows x 6 columns]

In [6]:
import numpy as np
import scipy.stats

In [9]:
def mean_confidence_interval(data, confidence=0.95):
    a = 1.0 * data
    n = len(a)
    m, se = np.mean(a), scipy.stats.sem(a)
    h = se * scipy.stats.t.ppf((1+confidence)/2, n-1)
    return m, h

In [10]:
df.groupby('Role').agg(
    Mean_Height=('Height', 'mean'),
    Count=('Age', 'count')
)

                   Mean_Height  Count
Role
Catcher             204.653333     75
Designated_Hitter   220.888889     18
First_Baseman       213.109091     55
Outfielder          199.113402    194
Relief_Pitcher      203.517460    315
Second_Baseman      184.344828     58
Shortstop           182.923077     52
Starting_Pitcher    205.163636    221
Third_Baseman       200.955556     45

In [12]:
for p in [0.85, 0.9, 0.95]:
    m1, h1 = mean_confidence_interval(df.loc[df['Role'] == 'First_Baseman', ['Height']], p)
    m2, h2 = mean_confidence_interval(df.loc[df['Role'] == 'Third_Baseman', ['Height']], p)
    print(f"p: {p}, 1st_Baseman_Height: {m1-h1[0]:.2f}..{m1+h1[0]:.2f}, 3rd_Baseman_Height: {m2-h2[0]:.2f}..{m2+h2[0]:.2f}")

p: 0.85, 1st_Baseman_Height: 209.36..216.86, 3rd_Baseman_Height: 196.99..204.92
p: 0.9, 1st_Baseman_Height: 208.82..217.40, 3rd_Baseman_Height: 196.41..205.50
p: 0.95, 1st_Baseman_Height: 207.97..218.25, 3rd_Baseman_Height: 195.51..206.41

# To test the hypothesis that first basemen are taller than third basemen

## We'll do the Student's t-test

In [14]:
from scipy.stats import ttest_ind

In [16]:
tval, pval = ttest_ind(df.loc[df['Role'] == 'First_Baseman', 'Height'], df.loc[df['Role'] == 'Third_Baseman', 'Height'], equal_var=False)
print(f"t_val: {tval:.2f}, p-value: {pval:.2f}")

t_val: 3.26, p-value: 0.00

> Since p-value is zero, we failed to reject the Alternate Hypothesis (H1)